language: python
python:
  "3.6.9"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run -m pytest
after_success:
  - codecov
  - curl --ftp-create-dirs
    -T filename
    sftp://${SFTP_USER}:${SFTP_PASSWORD}@{VDS_IP}/Age-Analyzer