name: Python coverage tests

on:
  push:
    branches: [master]


jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set environment variables
      - name: Run tests
        run: coverage run -m pytest
      - name: Tests report
        run: coverage report